"""High-exposure fact segment in the reasoning-v3 stream convention.

Why this exists. The reasoning-v3 corpus offloads 20.419% of base targets, but
measurement showed those spans are largely inferable: at 40M the split arm
recovered 94.2% of dense's score on them without ever training there, so
supervision was worth 0.33 of 5.73 nats. Masking content a model can deduce
frees nothing, which is why Memory Split measured a null at 8M, 40M and 160M.

This segment attacks both halves of that problem:

  exposure        each fact is rendered `n_exposures` times, in a different
                  surface form every time, so the model must learn the fact
                  rather than a sentence. bios.py has ~1.2e11 renderings per
                  entity, so 200 exposures collide with probability ~0.
  unpredictability attribute values are drawn independently of context from
                  invented vocabularies, so no amount of surrounding text
                  predicts them. This is the dial that sets the ceiling on any
                  dense-minus-split contrast.

Convention. Setup A gave the arms different text; the split rendering carried
lookup markers. Here both arms read ONE byte-identical stream and differ only
in a uint8 target-weight sidecar, matching reasoning-v3 so the resulting corpus
is a drop-in for the existing trainer, configs and analysis windows.
"""

from __future__ import annotations

from collections.abc import Iterator

import numpy as np

from corpusgen import bios
from corpusgen.records import ATTRIBUTES, BioRecord

# Measured on 40 entities x 3 exposures with the repo tokenizer.
TOKENS_PER_DOC_ESTIMATE = 73.6
BITS_PER_ENTITY_ESTIMATE = 50.1


def plan(budget_tokens: int, n_exposures: int,
         tokens_per_doc: float = TOKENS_PER_DOC_ESTIMATE) -> dict:
    """How many entities fit a token budget, and what that demands in bits.

    The three quantities trade off exactly: budget = entities x exposures x
    tokens_per_doc. Raising exposure to guarantee memorisation shrinks the fact
    universe, and the universe is what sets the storage burden.
    """
    n_entities = int(budget_tokens // (n_exposures * tokens_per_doc))
    bits = n_entities * BITS_PER_ENTITY_ESTIMATE
    return {
        "budget_tokens": budget_tokens,
        "n_exposures": n_exposures,
        "n_entities": n_entities,
        "n_docs": n_entities * n_exposures,
        "total_bits": bits,
        "bits_per_param": {
            "d8m": bits / 7_931_776,
            "d40m": bits / 40_560_000,
            "d160m": bits / 162_220_800,
        },
    }


def doc_order(n_entities: int, n_exposures: int) -> Iterator[tuple[int, int]]:
    """(entity_idx, exposure_idx) in grouped rounds: every entity once at
    exposure 0, then every entity at exposure 1, and so on.

    Spacing matters. Massed repetition -- all 200 copies of one fact adjacent --
    is memorised and then decayed; spreading each fact's exposures across the
    whole segment is what makes the model actually retain it, and it is the
    order realfact.py already uses.
    """
    for exposure in range(n_exposures):
        for entity in range(n_entities):
            yield entity, exposure


def encode_docs(
    records: list[BioRecord],
    order: Iterator[tuple[int, int]],
    tok,
) -> Iterator[tuple[np.ndarray, np.ndarray]]:
    """Yield (ids uint16, split_mask uint8) per document.

    The mask is 1 = loss ON, 0 = offloaded, matching train/data.py. The dense
    sidecar for the same tokens is all ones and is generated by the writer, not
    here, because both arms share these exact ids.
    """
    for entity, exposure in order:
        segs = bios.render_bio_marked(records[entity], exposure)
        ids, mask = tok.encode_segments(segs, add_eot=True)
        yield np.asarray(ids, dtype=np.uint16), np.asarray(mask, dtype=np.uint8)


def offloaded_fraction(records: list[BioRecord], tok, n_sample: int = 40) -> float:
    """Share of tokens that carry no loss in the split arm, for sizing."""
    on = off = 0
    for rec in records[:n_sample]:
        _, mask = tok.encode_segments(bios.render_bio_marked(rec, 0), add_eot=True)
        off += mask.count(0)
        on += len(mask)
    return off / max(1, on)


def verify_doc(rec: BioRecord, exposure: int, tok) -> None:
    """Assert the invariants a sidecar depends on. Cheap; call it while building.

    Checks that the masked token spans decode back to exactly the six attribute
    values. If a template ever lets a value appear in plain text as well, the
    split arm would see it unmasked elsewhere and the offload would leak.
    """
    segs = bios.render_bio_marked(rec, exposure)
    ids, mask = tok.encode_segments(segs, add_eot=True)
    masked_text = ""
    run: list[int] = []
    for i, m in enumerate(mask):
        if m == 0:
            run.append(ids[i])
        elif run:
            masked_text += tok.decode(run) + "\x00"
            run = []
    if run:
        masked_text += tok.decode(run) + "\x00"
    got = sorted(s.strip() for s in masked_text.split("\x00") if s.strip())
    want = sorted(rec.attrs[a] for a in ATTRIBUTES)
    if got != want:
        raise AssertionError(
            f"entity {rec.entity_id} exposure {exposure}: masked spans {got} != values {want}"
        )
    plain = "".join(t for t, m in segs if not m)
    for a in ATTRIBUTES:
        if rec.attrs[a] in plain:
            raise AssertionError(
                f"entity {rec.entity_id} exposure {exposure}: value for {a} leaks unmasked"
            )
