"""Deterministic metadata-first parallel corpus construction."""

from .adapters import UnsupportedProductionRenderer, UnsupportedSourceError
from .catalog import CatalogRecord, InputCatalog, fixture_catalog
from .integrity import ordered_stream_commitments, verify_stream_commitments
from .metadata import (
    FixtureRenderer,
    MetadataRecord,
    RenderedRecord,
    Renderer,
    metadata_from_bytes,
    metadata_to_bytes,
    reduce_metadata,
    render_metadata,
)
from .publication import (
    ParallelBuildConfig,
    VerifiedParallelCorpus,
    build_parallel_corpus,
    build_parallel_corpus_from_tasks,
    parallel_build_id,
    publish_verification_receipt,
    publication_staging_path,
    rerender_and_pack,
    verify_parallel_corpus,
)
from .safeio import (
    RETAINED_TOMBSTONE_ADMISSION_BYTE_THRESHOLD,
    RETAINED_TOMBSTONE_ADMISSION_COUNT_THRESHOLD,
    RetainedTombstoneAdmissionError,
    RetainedTombstoneIdentityError,
    RetainedTombstoneInventory,
    atomic_rename_noreplace,
    retained_tombstone_inventory,
    retained_tombstone_maintenance_contract,
)
from .tasks import (
    CachedTaskRecord,
    TaskResult,
    partition_ordinals,
    reduce_task_results,
    render_task_result,
    task_result_filename,
    task_result_from_bytes,
    task_result_to_bytes,
)
from .workspace import (
    IncompleteTaskResults,
    cleanup_task_workspace,
    local_task_workspace_path,
    load_task_results,
    publish_task_result,
    publish_task_result_via_local_cache,
    task_workspace_path,
)
from .schedule import (
    ScheduleRecord,
    ShardAssignment,
    assignments_from_bytes,
    assignments_to_bytes,
    assign_update_aligned_shards,
    largest_deficit_schedule,
    schedule_from_bytes,
    schedule_to_bytes,
)

__all__ = [
    "CatalogRecord",
    "CachedTaskRecord",
    "FixtureRenderer",
    "InputCatalog",
    "IncompleteTaskResults",
    "MetadataRecord",
    "ParallelBuildConfig",
    "RETAINED_TOMBSTONE_ADMISSION_BYTE_THRESHOLD",
    "RETAINED_TOMBSTONE_ADMISSION_COUNT_THRESHOLD",
    "RenderedRecord",
    "Renderer",
    "RetainedTombstoneAdmissionError",
    "RetainedTombstoneIdentityError",
    "RetainedTombstoneInventory",
    "ScheduleRecord",
    "ShardAssignment",
    "TaskResult",
    "UnsupportedProductionRenderer",
    "UnsupportedSourceError",
    "VerifiedParallelCorpus",
    "assign_update_aligned_shards",
    "atomic_rename_noreplace",
    "assignments_from_bytes",
    "assignments_to_bytes",
    "build_parallel_corpus",
    "build_parallel_corpus_from_tasks",
    "cleanup_task_workspace",
    "fixture_catalog",
    "largest_deficit_schedule",
    "local_task_workspace_path",
    "load_task_results",
    "metadata_from_bytes",
    "metadata_to_bytes",
    "ordered_stream_commitments",
    "parallel_build_id",
    "partition_ordinals",
    "publication_staging_path",
    "publish_task_result",
    "publish_task_result_via_local_cache",
    "publish_verification_receipt",
    "reduce_metadata",
    "reduce_task_results",
    "render_metadata",
    "render_task_result",
    "retained_tombstone_inventory",
    "retained_tombstone_maintenance_contract",
    "rerender_and_pack",
    "schedule_from_bytes",
    "schedule_to_bytes",
    "task_result_filename",
    "task_result_from_bytes",
    "task_result_to_bytes",
    "task_workspace_path",
    "verify_parallel_corpus",
    "verify_stream_commitments",
]
